/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Channel = t.iface([], {
  displayName: t.opt("string"),
  functionID: t.opt("string"),
  room: t.opt("string"),
  floor: t.opt("string"),
  inputs: t.opt(
    t.iface([], {
      [t.indexKey]: "InOutPut",
    })
  ),
  outputs: t.opt(
    t.iface([], {
      [t.indexKey]: "InOutPut",
    })
  ),
  type: t.opt("string"),
});

const exportedTypeSuite: t.ITypeSuite = {
  Channel,
};
export default exportedTypeSuite;
