/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Configuration = t.iface([], {
  [t.indexKey]: "SysAP",
});

const exportedTypeSuite: t.ITypeSuite = {
  Configuration,
};
export default exportedTypeSuite;
