/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Device = t.iface([], {
  displayName: t.opt("string"),
  room: t.opt("string"),
  floor: t.opt("string"),
  interface: t.opt("string"),
  nativeId: t.opt("string"),
  channels: t.opt(
    t.iface([], {
      [t.indexKey]: "Channel",
    })
  ),
});

const exportedTypeSuite: t.ITypeSuite = {
  Device,
};
export default exportedTypeSuite;
