/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const DeviceResponse = t.iface([], {
  [t.indexKey]: t.iface([], {
    devices: "Devices",
  }),
});

const exportedTypeSuite: t.ITypeSuite = {
  DeviceResponse,
};
export default exportedTypeSuite;
