/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const DeviceList = t.iface([], {
  [t.indexKey]: t.iface([], {
    deviceSerialNumber: t.array("string"),
  }),
});

const exportedTypeSuite: t.ITypeSuite = {
  DeviceList,
};
export default exportedTypeSuite;
