/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Devices = t.iface([], {
  [t.indexKey]: "Device",
});

const exportedTypeSuite: t.ITypeSuite = {
  Devices,
};
export default exportedTypeSuite;
