/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Error = t.iface([], {
  code: "string",
  detail: "string",
  title: "string",
});

const exportedTypeSuite: t.ITypeSuite = {
  Error,
};
export default exportedTypeSuite;
