/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const InOutPut = t.iface([], {
  value: t.opt("string"),
  pairingID: t.opt("number"),
});

const exportedTypeSuite: t.ITypeSuite = {
  InOutPut,
};
export default exportedTypeSuite;
