/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Rooms = t.iface([], {
  [t.indexKey]: t.iface([], {
    name: "string",
  }),
});

const exportedTypeSuite: t.ITypeSuite = {
  Rooms,
};
export default exportedTypeSuite;
