/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const ScenesTriggered = t.iface([], {
  [t.indexKey]: t.iface([], {
    channels: t.iface([], {
      [t.indexKey]: t.iface([], {
        outputs: t.iface([], {
          [t.indexKey]: t.iface([], {
            value: "string",
            pairingID: "number",
          }),
        }),
      }),
    }),
  }),
});

const exportedTypeSuite: t.ITypeSuite = {
  ScenesTriggered,
};
export default exportedTypeSuite;
