/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Users = t.iface([], {
  [t.indexKey]: t.iface([], {
    enabled: "boolean",
    flags: t.array("string"),
    grantedPermissions: t.array("string"),
    jid: "string",
    name: "string",
    requestedPermissions: t.array("string"),
    role: "string",
  }),
});

const exportedTypeSuite: t.ITypeSuite = {
  Users,
};
export default exportedTypeSuite;
