/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const WebSocketMessage = t.iface([], {
  systemAccessPoint: t.iface([], {
    [t.indexKey]: t.iface([], {
      datapoints: t.iface([], {
        [t.indexKey]: "string",
      }),
      devices: t.iface([], {
        [t.indexKey]: "Devices",
      }),
      devicesAdded: t.array("string"),
      devicesRemoved: t.array("string"),
      scenesTriggeres: "ScenesTriggered",
    }),
  }),
});

const exportedTypeSuite: t.ITypeSuite = {
  WebSocketMessage,
};
export default exportedTypeSuite;
